# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-04-10 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('count_subscribes', models.IntegerField(default=0)),
                ('descriptions', models.CharField(max_length=500)),
            ],
        ),
    ]
